export class ProductsActions {
  static CALL_SUBSCRIBE_PRODUCTS = "CALL_SUBSCRIBE_PRODUCTS";
  static CALL_UNSUBSCRIBE_PRODUCTS = "CALL_UNSUBSCRIBE_PRODUCTS";
  static LOAD_PRODUCTS_FROM_COLLECTION = "LOAD_PRODUCTS_FROM_COLLECTION";
  static ADD_PRODUCTS = "ADD_PRODUCTS";
  static PRODUCTS_COLLECTION_UPDATED = "PRODUCTS_COLLECTION_UPDATED";
}